version: '3'

services:
  unicorn:
    image: cxsz16888/sehuatang:latest
    container_name: sehuatang
    restart: unless-stopped
    volumes:
      # 挂载配置文件目录
      - ./config:/app/config
      # 挂载日志目录
      - ./logs:/app/logs
    environment:
      # 设置时区
      - TZ=Asia/Shanghai
    # 使用Python脚本作为入口点
    command: python run.py 